# Settings common to all machines
---
# Extra COPR repos for convenience on EL-7
core_copr_repos:
  - 'hnakamur/vim'
  - 'jstanek/server-ports'

human_users:
  - login: khardix
    password: >-
      $6$hicsuntdracones$64mhvYmHPAox4juGNdyqxfId2S.F3a2TcgTnU2T9Dvmq8ebfc/JtlpgF.Hxt5QL4.zgC8ua3mzoU3hM5BHFqY1
    groups: [wheel]
    shell: /bin/zsh
    home_git: https://git.sr.ht/~khardix/homedir
    ssh_key: >-
      ssh-ed25519
      AAAAC3NzaC1lZDI1NTE5AAAAIABrLcUAORKMejx5ZHm2rtjmchY58JFz58X9sNv/PfRR
      openpgp:0xC5CC249C
...
