---
- name: Open new ssh port in firewall
  ufw: port=443 proto=tcp rule=allow

- name: Switch to SSLH
  set_fact: ansible_port=443
  when:
    - not ansible_host.lower().startswith('192.168.')
    - not ansible_host.lower().startswith('fe80:')

- name: Verify existing connection
  ping: ~

- name: Close old ssh port in firewall
  ufw: delete=true port=ssh rule=allow

- name: Listen only on localhost
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*ListenAddress'
    line: 'ListenAddress localhost'
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Reload sshd

- name: Add root key
  when: ssh_root_key is defined
  authorized_key: user=root key={{ssh_root_key}}

- name: Tighten root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    # yamllint disable-line rule:line-length
    line: PermitRootLogin {% if ssh_root_key is defined %}without-password{% else %}no{% endif %}
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Reload sshd

- name: Disable password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: PasswordAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Reload sshd
