---
- name: Install ufw
  package: name=ufw state=present
  register: install_ufw

- name: Disable IPv6 if unsupported
  lineinfile:
    state: present
    path: /etc/default/ufw
    regexp: '^IPV6='
    line: 'IPV6=no'
  when:
    - install_ufw is changed
    - >-
      ansible_all_ipv6_addresses is undefined
      or not ansible_all_ipv6_addresses

- name: Clear ufw rules
  when: install_ufw is changed
  loop:
    - user
    - user6
  blockinfile:
    path: '/var/lib/ufw/{{item}}.rules'
    state: absent
    marker: '### {mark} ###'
    marker_begin: RULES
    marker_end: END RULES
  register: clear_ufw_rules

- name: Re-enable ssh
  when: clear_ufw_rules is changed
  become: true
  ufw: rule=allow port=ssh
  register: ufw_reenable_ssh
  retries: 5
  delay: 1
  until: ufw_reenable_ssh is succeeded

# The ufw module/command tends to fail when ufw daemon is not running
# Enable it uncoditionally now, so the dependent roles
# do not have to care about that
- name: Enable ufw internally
  ufw: state=enabled policy=deny direction=incoming
  tags: [firewall]

- name: Enable ufw in systemd
  systemd: service=ufw state=started enabled=true
  tags: [firewall]
