---
- name: Install firewalld
  package: name=firewalld state=present
  notify: Enable firewalld service

- name: Switch to {{firewalld_zone}} zone
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^#? ?DefaultZone='
    line: 'DefaultZone={{firewalld_zone}}'
  notify: Reload firewalld service
