---
- hosts: daidalos.khardix.cz
  become: true
  gather_facts: false
  pre_tasks:
    - name: Check for correct SSH port
      include_tasks: tasks/determine-ssh-port.yml
      when:
        - ansible_port is defined
        - ansible_port != 22
      tags: [always]
    - name: Gather facts
      setup: ~
      tags: [always]

  roles:
    - role: khardix.multi-user  # includes hardened-ssh
      tags: [bootstrap]
    - role: khardix.taskd
