---
- hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    - name: Check for correct SSH port
      include_tasks: tasks/determine-ssh-port.yml
      when:
        - ansible_port is defined
        - ansible_port != 22
    - name: Gather facts
      setup: ~

  roles:
    - name: khardix.sslh
      sslh_service: ssh
      sslh_port: 22
