---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Check for correct SSH port
      include_tasks: tasks/determine-ssh-port.yml
      when:
        - ansible_port is defined
        - ansible_port != 22
      tags: [always]
    - name: Gather facts
      setup: ~
      tags: [always]

  roles:  # Basic setup
    - role: khardix.multi-user  # includes hardened-ssh
      tags: [bootstrap]

  tasks:
    # Dynamic roles
    - name: Configure taskwarrior server
      include_role:
        name: khardix.taskd
        apply: {tags: [taskd]}
      tags: [taskd]

    - name: Configure static sites
      tags: [website]
      include_role:
        name: khardix.website
        apply: {tags: [website]}
      loop: '{{hosted_static_sites|default([])}}'
      loop_control: {loop_var: website}
      vars:
        website_owner: '{{website.owner}}'
        website_hostname_list: '{{website.hostname_list}}'
