---
galaxy_info:
  author: Jan "Khardix" Staněk
  description: Service specification for SSLH multiplexing
  issue_tracker_url: https://gitlab.com/khardix/server-setup/issues

  license: AGPLv3+

  min_ansible_version: 2.5

  platforms:
    - name: CentOS
      versions:
        - 7

dependencies:
  - khardix.sslh
