---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
platforms:
  - name: instance-centos
    image: centos:7
    volume_mounts: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    command: '/usr/sbin/init'
  - name: instance-alpine
    image: alpine:3
    volume_mounts: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    command: '/sbin/init'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
