---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos:7
    privileged: true
    volume_mounts: ['/sys/fs/cgroup:/sys/fs/cgroup:ro']
    command: '/usr/sbin/init'
    environment:
      container: docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
