---
- name: Install taskd server
  package: name=khardix-taskd state=present
  notify: Enable taskd service

- name: Generate server certificates
  command: /usr/lib/taskd/pki/generate
  args:
    creates: /etc/pki/taskd/client.cert.pem

- name: Open firewall port for taskd
  ufw: port=53589 proto=tcp rule=allow comment=taskd
