---
galaxy_info:
  author: Jan "Khardix" Staněk
  description: Base firewall setup
  issue_tracker_url: https://gitlab.com/khardix/server-setup/issues
  license: AGPLv3+
  min_ansible_version: 2.5
  platforms:
    - name: CentOS
      versions:
        - 7
  galaxy_tags: []

dependencies: []
