---
galaxy_info:
  author: Jan “Khardix” Staněk
  description: nftables-based simple firewall
  license: AGPL-3.0-or-later
  min_ansible_version: 2.7
  platforms:
    - name: Alpine
      versions:
        - all
    - name: CentOS
      versions:
        - 7
  galaxy_tags: []

dependencies: []
...
