---
- name: Install nginx
  package:
    name: [nginx, nginx-mod-http-perl]
    state: present
  notify: Start nginx

- name: Enter {{ssl_access_group}} group
  user:
    name: nginx
    groups:
      - '{{ssl_access_group}}'
    append: true

- name: Install main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    group: nginx
    mode: 0644
  notify: Reload nginx configuration

- name: Open http/https ports in firewall
  firewalld:
    service: '{{item}}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - http
    - https

- name: Install drop-in for certificate renewal
  copy:
    src: reload-nginx.conf
    dest: '{{ssl_service_dir}}/reload-nginx.conf'
  notify: Reload ssl unit definition

- name: Prepare configuration directory for virtual hosts
  file:
    path: /etc/nginx/sites
    state: directory
    group: nginx
    mode: 0755
