---
- name: Install required packages
  package:
    state: present
    name:
      - 'perl(List::MoreUtils)'
      - 'perl(Locale::Util)'
      - 'perl(Test::Simple)'
      - dehydrated
      - gnutls-utils
      - nginx
      - nginx-mod-http-perl
      - openssl

# Bootstrap TLS, so that nginx can start before dehydrated
- import_tasks: tls-bootstrap.yml
# Configure common nginx settings
- import_tasks: nginx.yml
# Configure Let's Encrypt certificate automation
- import_tasks: dehydrated.yml
