---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "Create test user"
      user: name=example_user
  roles:
    - role: "khardix.website"
      website_hostname_list: [example.com]
      website_owner: example_user
