---
- name: Install core packages
  package:
    name: '{{ core_packages[ansible_facts.os_family|lower] }}'
    state: present


# ### Network configuration ###################################################
- name: Provide {{ override_fqdn|default(ansible_facts.fqdn) }} entries in /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    unsafe_writes: true  # needed in container

# ### Logging management ######################################################
- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: Reload rsyslog

- name: Configure log rotation
  block:
    - name: Configure /etc/logrotate.conf
      template:
        src: logrotate.conf.j2
        dest: /etc/logrotate.conf
    - name: Configure /etc/logrotate.d/rsyslog
      template:
        src: logrotate.d/rsyslog.j2
        dest: /etc/logrotate.d/rsyslog
    - name: Schedule log rotation (cron)
      vars:
        dest:
          alpine: /etc/periodic/daily
          redhat: /etc/cron.daily
      copy:
        src: periodic/logrotate
        dest: '{{ dest[ansible_facts.os_family|lower] }}/logrotate'
        mode: 0744


- name: Modify core services
  loop: '{{ core_services[ansible_facts.os_family|lower] }}'
  loop_control:
    label: '{{ item.name|default(item) }}: {{ "enabled" if item.enabled|default(true) else "disabled" }}'
  service:
    name: '{{ item.name|default(item) }}'
    state: '{{ item.state|default(omit) }}'
    enabled: '{{ item.enabled|default(true) }}'
    runlevel: '{{ item.runlevel|default("default") }}'
  notify: Reboot the machine
...
