---
- name: Install core packages
  package:
    name: '{{ core_packages[ansible_facts.os_family|lower] }}'
    state: present


# ### Logging management ######################################################
- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: Restart rsyslog

# ### Network configuration ###################################################
- name: Provide {{ override_fqdn|default(ansible_facts.fqdn) }} entries in /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts
    unsafe_writes: true  # needed in container


- name: Enable core services
  loop: '{{ core_services[ansible_facts.os_family|lower] }}'
  service:
    name: '{{ item }}'
    state: started
    enabled: true
...
