---
ansible_user: khardix
ansible_become_pass: '{{lookup("passwordstore", "sudo/daidalos.khardix.cz")}}'
ansible_port: 443

letsencrypt_contact_email: 'khardix@gmail.com'

hosted_static_sites:
  - hostname_list: [khardix.cz, www.khardix.cz]
    owner: khardix
