# Make remote-hosted files available locally on the controller
---
- name: Prepare local directory for MineCraft files
  become: false
  local_action:
    module: file
    path: files/minecraft/vendor
    state: directory
  register: minecraft_vendor_dir

- name: Download server packs to controller
  become: false
  loop: '{{ minecraft_pack_list|map(attribute="server_pack")|select|list }}'
  loop_control: &vendor-item-control
    label: '{{ item.url|urlsplit("path")|basename }}'
  local_action:
    module: get_url
    url: '{{ item.url|default(item) }}'
    checksum: '{{ item.checksum|default(omit) }}'
    dest: '{{ minecraft_vendor_dir.path }}'
    mode: 0644

- name: Download extra mods to controller
  become: false
  loop: >-
    {{ minecraft_pack_list
    |selectattr("extra_mods", "defined")
    |map(attribute="extra_mods")
    |flatten|unique
    |list }}
  loop_control: *vendor-item-control
  local_action:
    module: get_url
    url: '{{ item.url|default(item) }}'
    checksum: '{{ item.checksum|default(omit) }}'
    dest: '{{ minecraft_vendor_dir.path }}'
    mode: 0644
...
