---
dependencies:
  - role: khardix.sslh
  - role: khardix.firewall

galaxy_info:
  author: Jan "Khardix" Staněk
  description: Hardens SSH configuration
  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: CentOS
      versions: [6, 7]

  galaxy_tags:
    - repository
    - epel
