---
- name: Install sslh package
  package: name=sslh state=installed

- name: Create snippets directory
  file: path=/etc/sslh.d/proto.d state=directory

- name: Install configuration file
  template: src=sslh.cfg.j2 dest=/etc/sslh.cfg
  notify:
    - Assemble SSLH protocol configuration
    - Reload SSLH

- name: Prepare initial configuration
  meta: flush_handlers

- name: Start and enable sslh.service
  service: name=sslh.service state=started enabled=true
