---
- name: Install sslh package
  package: name=sslh state=installed

- name: Install service file
  copy: src=sslh.service dest=/etc/systemd/system/sslh.service
  notify:
    - Reload SSLH

- name: Install socket file
  template: src=sslh.socket dest=/etc/systemd/system/sslh.socket
  notify:
    - Reload SSLH

- name: Create snippets directory
  file: path=/etc/sslh.d/proto.d state=directory

- name: Install configuration file
  copy: src=sslh.cfg dest=/etc/sslh.cfg
  notify:
    - Reload SSLH
