---
- name: Install sslh package
  package: name=sslh state=installed

- block:
    - name: Install service file
      copy: src=sslh.service dest=/etc/systemd/system/sslh.service
      notify:
        - Reload sslh
    - name: Install socket file
      template: src=sslh.socket dest=/etc/systemd/system/sslh.socket
      notify:
        - Reload sslh

- block:
    - name: Create snippets directory
      file: path=/etc/sslh.d/proto.d state=directory
    - name: Create configuration snippet
      template: src=service.cfg dest=/etc/sslh.d/proto.d/{{sslh_port}}-{{sslh_service}}.cfg
      notify:
        - Assemble protocol configuration
    - name: Install configuration file
      copy: src=sslh.cfg dest=/etc/sslh.cfg
      notify:
        - Reload sslh

- name: Configure sshd
  blockinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^#ListenAddress '
    block: |
      ListenAddress localhost
      {% for addr in ansible_all_ipv4_addresses if addr.startswith('192.168.') %}
      ListenAddress {{addr}}
      {% endfor %}
      {% for addr in ansible_all_ipv6_addresses if addr.lower().startswith('fe80:') %}
      ListenAddress [{{addr}}]
      {% endfor %}
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Reload sshd

- name: Apply changes to SSH
  meta: flush_handlers

- name: Redirect to new ssh port
  set_fact: ansible_port=443
  when:
    - not ansible_host.lower().startswith('192.168.')
    - not ansible_host.lower().startswith('fe80:')

- name: Verify existing connection
  ping:
