---
- name: Install sslh and supporting packages
  package:
    name: '{{ sslh_packages[ansible_os_family|lower] }}'
    state: present

- name: Install configuration file
  template: src=sslh.cfg.j2 dest=/etc/sslh.cfg

- name: Install systemd service
  copy:
    src: sslh.service
    dest: /etc/systemd/system/sslh.service

- name: Start and enable sslh.service
  service: name=sslh.service state=started enabled=true daemon_reload=true
