---
- name: Install sslh and supporting packages
  package:
    name: '{{ sslh_packages[ansible_os_family|lower] }}'
    state: present

- name: Provide sslh user and group
  block:
    - name: Provide sslh group
      group:
        name: sslh
        state: present
        system: true
    - name: Provide sslh user
      user:
        state: present
        name: sslh
        group: sslh
        system: true
        shell: /sbin/nologin
        create_home: false

- name: Configure sslh
  block:
    - name: Provide /etc/sslh directory
      file:
        path: /etc/sslh
        state: directory
        mode: 0755
    - name: Generate /etc/sslh/sslh.cfg
      template:
        src: sslh.cfg.j2
        dest: /etc/sslh/sslh.cfg
        mode: 0644
        group: sslh

- name: Install service file
  vars:
    sslh_service:
      systemd:
        src: sslh.service
        dest: /etc/systemd/system/sslh.service
        mode: '0644'
      openrc:
        src: sslh.initd
        dest: /etc/init.d/sslh
        mode: '0744'
  copy:
    src: '{{ sslh_service[ansible_service_mgr].src }}'
    dest: '{{ sslh_service[ansible_service_mgr].dest }}'
    mode: '{{ sslh_service[ansible_service_mgr].mode }}'


- name: Start and enable sslh service
  block:
    - name: Reload systemd definition
      when: ansible_service_mgr == "systemd"
      systemd: daemon_reload=true
    - name: Enable and start sslh service
      service:
        name: sslh
        state: started
        enabled: true
