---
- name: Install sslh and supporting packages
  package:
    name: '{{ sslh_packages[ansible_os_family] }}'
    state: present
    update_cache: true

- name: Provide /usr/libexec/sslh
  file:
    path: /usr/libexec/sslh
    state: directory
    owner: sslh
    mode: 0755

- name: Install configuration generator
  copy:
    src: generate-listeners.py
    dest: /usr/libexec/sslh/generate-listen.py
    mode: 0750
    owner: sslh

- name: Install configuration file
  copy: src=sslh.cfg dest=/etc/sslh.cfg

- name: Install systemd service
  copy:
    src: sslh.service
    dest: /etc/systemd/system/sslh.service

- name: Start and enable sslh.service
  service: name=sslh.service state=started enabled=true daemon_reload=true
