galaxy_info:
  author: Jan “Khardix” Staněk
  description: Generic Ansible role
  license: AGPL-3.0-or-later
  min_ansible_version: 2.7
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags: []
dependencies: []
